### ISSUE TITLE
When will the data be accessible?

### ISSUE THREAD

**Issue by LinB203** [DCDmllm/Momentor#1]
Great job! This is a huge boost to Video-LLM.
I wonder that when will the data be accessible?

**Comment by longqian-zju** [comment]
Thank you for your interest in our dataset!

We are currently organizing and packaging both the data and the code. Once this process is complete, we will make the dataset and code publicly available. I guess it will be finished in March.

**Comment by gunnarmarino** [comment]
Hey! Status update? I'm excited!

**Comment by longqian-zju** [comment]
> Hey! Status update? I'm excited!

Thank you for your interest in our dataset!

Sorry but the data filtering and cleaning take longer time than expected. I will release the full dataset in March or early April if this process could finish in time. Otherwise, I'll consider releasing the first half of the dataset first. It will be no later than April though. Thanks again for your attention!

**Comment by gunnarmarino** [comment]
Great to hear. Same timeline for the code?

**Comment by longqian-zju** [comment]
We have temporarily released the first half of the Moment-10M dataset (with ~32000 videos and ~5M instruction following data), and the remaining half will be made available soon after we finalize our filtering and cleaning process (I guess it will take no more than one week).
