### ISSUE TITLE
Code Availability

### ISSUE THREAD

**Issue by anilbatra2185** [DCDmllm/Momentor#4]
Hi @longqian-zju ,

Thank you for sharing the data and great work. Requesting to share the code for reproducibility.

Thanks

**Comment by longqian-zju** [comment]
Thank you for your interest in our work!

We have released the code for Momentor, but it may contain some errors and could be a little bit messy. Since I'm currently busy with another project, I might not have enough time for a thorough review. Let me know if you encounter any difficulties while running our code.
